import React, { useState } from 'react';
import { NavLink } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { Modal } from '../../context/Modal';
// import ProfileButton from './ProfileButton';
// import LoginFormModal from '../LoginFormModal';
// import SignupFormModal from '../SignupFormModal';
// import AddNewSpotModal from '../AddNewSpotModal/index.js';
// import AddNewSpotForm from '../AddNewSpotModal/AddNewSpotForm';
import './Navigation.css';
